### ISSUE TITLE
Navigation hamburger

### ISSUE THREAD

**Issue by QjStout** [codesydney/codesydney#21]
### What?
A global component that will appear on every page. Goes in /src/App.vue
Shows a hamburger icon and when clicked a navigation menu folds/slides out.

**Does not** require creating the navigation system. This is just for component that displays navigation.
Use dummy values for foldout menu until there is a navigation system.

### Visual reference:
![homepage-rework-proto-nav-hamburger](https://user-images.githubusercontent.com/19155822/87613059-88d18e00-c74f-11ea-92c1-f261360cf17b.png)

**Comment by kimchirice** [comment]
@QjStout 
  I will give it a go

**Comment by QjStout** [comment]
Thanks, @kimchirice!
Issue has been assigned to you.
