### ISSUE TITLE
Homepage - member profile widget

### ISSUE THREAD

**Issue by QjStout** [codesydney/codesydney#22]
### What?
We want to display Code.Sydney members and link to their profile pages.
Current suggestion is to present it in the following format:
  * Member portrait
  * Name
  * Role
  * Badges - on hover, display badge title
  * Member contact page link, or socials or something

Badges are a separate issue as there may be functionality added, so just put a couple code.sydney logos and placeholder badge titles.

### Visual Reference:
Use the circled reference
![homepage-rework-proto-developer-profile-widgets](https://user-images.githubusercontent.com/19155822/87618793-10be9480-c75e-11ea-924e-7930e34abecb.png)

**Comment by chenhe-henry** [comment]
Hi Qj, I'm Chen, I'm interested in this issue.

**Comment by QjStout** [comment]
Hey @chenhe-henry!
Thanks for putting your hand up.
I've assigned this issue to you. Let me know if you have any questions.
