### ISSUE TITLE
Member badge system

### ISSUE THREAD

**Issue by QjStout** [codesydney/codesydney#24]
### What?
The idea is to reward Code.Sydney volunteers for their achievements, in a manner that aids in their promotion to prospective PAYF clients & employers.

##### A badge is made up of:
1. a small, square image. Think favicons, but maybe slightly larger.
2. a name, e.g. 'Vue Master'
3. a description, e.g. 'Received for completing the entire Vue Mastery course'

##### Badges should:
1. have a template that displays the badge image, and
2. on hover displays the badge name
3. have getters for the 3 values they consist of

### Additional Considerations:
As this is currently a front-end only project, you will need to use an array for storage as a placeholder.
I think the idea would be to create a Vue.js component and an additional data service. Put this storage in /services/badges.js

### Visual Reference:
![homepage-rework-proto-developer-profile-widgets](https://user-images.githubusercontent.com/19155822/87619934-a824e700-c760-11ea-97ea-5a3ceb75f9cd.png)

**Comment by engramar** [comment]
Hello @QjStout, I will take this onboard. We will use https://info.badgr.com/ for easier management of badge issuance. I will ask @chenhe-henry about the placement on the homepage if ever. Thanks.

**Comment by QjStout** [comment]
Perfect 👌

**Comment by engramar** [comment]
Thanks @QjStout . I am starting to get used to checking notifications now here in GitHub. It is actually my first time to experience something like this (ie.  very active collaboration within GitHub). Pretty cool! Thanks! =)

**Comment by QjStout** [comment]
It's great, right? I'm new to it also. Only started with Strataly.

**Comment by engramar** [comment]
Yes. I normally do everything by myself in GitHub hence not that much collaboration experience like this and this method of commenting to issues is pretty handy. As we said earlier, everything in one place. 

I hope all other Code.Sydney members will contribute their own page (ie. profile page) once the homepage is all set so they also experience this type of GitHub collaboration.
