### ISSUE TITLE
Contact Page - Calendly + Zoom integration

### ISSUE THREAD

**Issue by QjStout** [codesydney/codesydney#32]
### What?
Calendly integration that can be used to book Zoom meetings with Engramar.

**Comment by thechintan123** [comment]
@QjStout  - I am interested to take this up...

**Comment by QjStout** [comment]
Okay @thechintan123,

I see you participated in our Real World Vue group activity so I'm happy to assign this to you. Just an FYI, I have not researched what this issue requires so there could be snags. If you run into trouble ask @engramar for help as I believe he implemented this on the original site.

Good luck! 🥳

**Comment by thechintan123** [comment]
Thanks @QjStout 
I will also reach out to @engramar for guidance.

**Comment by thechintan123** [comment]
Hi @QjStout 
I have reached out to @engramar and he did share me the Calendly Widget script.
I have added that in CalendlyWidget.vue. This widget is incorporated in Contact Form

**Comment by thechintan123** [comment]
![image](https://user-images.githubusercontent.com/64998391/88920568-6cd1fe80-d2b0-11ea-9e49-ce5911c4112c.png)

**Comment by thechintan123** [comment]
Should I git push the changes..?

**Comment by thechintan123** [comment]
The changes are following:
1) Created a new CalendyWidget.vue
2) Added above component in ContactForm.vue
3) Added script of Calendly widget in index.html

**Comment by QjStout** [comment]
Hey @thechintan123! Looks good there man.
Instructions for submitting your first PR are on the repo README.

The gist of it is:
1. Commit your changes locally.
2. Push your feature branch to the repo - Descriptive name about your feature.
3. Go to the GitHub repo in your browser and submit a new Pull Request.
4. Wait for people to review your code.
5. Fix any change requests or finalise merge if your code is approved.

**Comment by thechintan123** [comment]
Sure @QjStout. I will push the changes to GitHub.
I saw your reply in Slack. Going forward, I will ensure to communicate through GitHub. I feel that would be convenient for all. :-)

**Comment by QjStout** [comment]
Sounds good man. Let me know if you run into trouble.
Add @chenhe-henry as an assignee so he can practice doing a code review.
