### ISSUE TITLE
Contact Page - Email form

### ISSUE THREAD

**Issue by QjStout** [codesydney/codesydney#33]
### What?
Pretty simple one.
Email form that hits up info@code.sydney.

#### Takes:
1. Name
2. Their email address
3. Their message

**Comment by QjStout** [comment]
This issue will be assigned to @kimchirice, pending him joining this repo.

**Comment by kimchirice** [comment]
- I am working with Jay AT THE MOMENT, see how he'd like to approach this one

**Comment by kimchirice** [comment]
[status update] @ 18/07/2020
  - Jay planned to get comfy first with Git CLI, he and I will have a follow-up discuss the mid of next week
  - my initial thoght, 
    1. [Add] a base contact form component file named *ContactForm.vue*, under [/client/src/compoents folder](https://github.com/codesydney/codesydney/tree/master/client/src/components)
    2. import it to the page [/client/src/views/Contact.vue](https://github.com/codesydney/codesydney/blob/master/client/src/views/Contact.vue)
    3. might need to refer to previous build, of how to "post" the data, which sort of sending it back to home 
```html
  <form data-bss-recipient="50e723e2d34f5df51ec3ded43a1838ce" method="POST" action="/"></form>
```

**Comment by kimchirice** [comment]
hi @QjStout , for the form, where did you want the form to be "posted",  once data collected? notice my own comment,  it was '/' on code.sydney current web. am I missing anything??

`  <form data-bss-recipient="50e723e2d34f5df51ec3ded43a1838ce" method="POST" action="/"></form>`

**Comment by QjStout** [comment]
As discussed with @kimchirice on Slack, the route to POST to is unknown until the back-end design sprint.
