### ISSUE TITLE
Interim Members API Endpoint

### ISSUE THREAD

**Issue by engramar** [codesydney/codesydney#56]
As agreed with @QjStout , we will develop a throw away code to expose member records via a new API endpoint. Flask-RESTPlus and SQLite will be used.

**Comment by engramar** [comment]
@QjStout, You can quickly test it using this link https://www.code.sydney/api/documentation
As this is outside our codebase, I can just proceed and close this one. Cheers!

**Comment by QjStout** [comment]
Looks good @engramar, thank you. And thank you for that convenient way to view it on mobile.

**Comment by engramar** [comment]
Welcome mate
