### ISSUE TITLE
Skeleton loader for member profiles

### ISSUE THREAD

**Issue by QjStout** [codesydney/codesydney#65]
Implement a skeleton loader that fills the screen space that the member profiles will take up once loaded, a la beach ball of death.

https://vuetifyjs.com/en/components/skeleton-loaders/

**Comment by kimchirice** [comment]
good on you @QjStout, was thinking of implementing it without adding another library, but hey... who knows 

I havent started anything solid yet. working on my other tasks, #52  and #25 AT THE MOMENT, but will be watching this issue at the same time.

**Comment by QjStout** [comment]
No problem @kimchirice. 
I'm happy with however anyone wants to solve it really.

**Comment by Prashanga** [comment]
Do we still need this feature? The list of all members is way below the visible section when the page first loads, and the random member skeleton loader is already there.

**Comment by QjStout** [comment]
Yeah probably not @Prashanga. Thanks for pointing that out.
