### ISSUE TITLE
Skeleton loader for 'random member' headline

### ISSUE THREAD

**Issue by QjStout** [codesydney/codesydney#73]
https://vuetifyjs.com/en/components/skeleton-loaders/
 - Alternatively
https://vuetifyjs.com/en/components/progress-circular/

**Comment by kimchirice** [comment]
I will give it a go, actually I've been mocking with Vuetify skeleton loader this afternoon.

**Comment by kimchirice** [comment]
sorry, just saw Qj is the assignee. I will pick the other issue, if I remember right there's another one of skeletion loader task.

**Comment by QjStout** [comment]
Happy to pass it on to you @kimchirice. I was having a lot of trouble with it. 
Getting a skeleton up is easy, but I can't figure out a way to load the actual component in the background before toggling the renders.

**Comment by Prashanga** [comment]
Hey, is this issue still up for grab? I will have a look

**Comment by QjStout** [comment]
Thanks @Prashanga. Just lodge a PR and add me & Promie as reviewers when you're ready.
