### ISSUE TITLE
Add banner to all pages

### ISSUE THREAD

**Issue by QjStout** [codesydney/codesydney#75]
### Reference:
![banner-requirement](https://user-images.githubusercontent.com/19155822/91518103-bb67cc80-e932-11ea-837b-3d756c8b3b66.PNG)

### Note:
If it doesn't look good, we can use the current banner on the homepage and have a thin navbar type banner on other pages.

**Comment by engramar** [comment]
@QjStout Yes. Feel free to experiment and see what suits best. Thanks.

**Comment by QjStout** [comment]
Currently thinking that the full-size banner should be on the Homepage only and a thin bar banner with the CodeSydney logo and name should be on the other pages.

**Comment by engramar** [comment]
Sounds good @QjStout
