### ISSUE TITLE
Add padding to the bottom of the email form.

### ISSUE THREAD

**Issue by QjStout** [codesydney/codesydney#86]
The submit button touches the bottom of the screen.
Simple issue, just add a little padding.

*** Reference:
![contactformpaddingissue](https://user-images.githubusercontent.com/19155822/95288184-729d1f00-08b3-11eb-85ba-73a6a9b90f51.jpg)

**Comment by AlexandreHiroyuki** [comment]
Hey. I'm interested in solving this problem to start learning about this project. It's cool that this project uses Vue since I didn't see many more projects using it.
