### ISSUE TITLE
On screen - Hamburger hidden 

### ISSUE THREAD

**Issue by webdiego** [codesydney/codesydney#89]
When is on screen , the hamburger button is too much on the right and for half part is hidden

**Comment by QjStout** [comment]
I'm not sure what you mean @webdiego.
Could you provide a visual reference to describe the issue?

**Comment by webdiego** [comment]
![20201011_145356.jpg](https://user-images.githubusercontent.com/63283003/95669973-b05eb800-0bd1-11eb-96bd-cdb7af63a5fa.jpg)

**Comment by webdiego** [comment]
The width of the navbar is greater than the container/body

**Comment by QjStout** [comment]
That's the old website @webdiego, not the one this project is for.
It's not hosted on the Codesydney URL yet because it's still a work in progress.

*** New website project:
https://code-dot-sydney.netlify.app/

**Comment by webdiego** [comment]
Ah...so I'm sorry for that😅

**Comment by QjStout** [comment]
All good man. No harm no foul 😄
